### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mitchellsimoens** [DianaIonita/serverless-api-gateway-caching#101]
HI,

I was wondering if you would be willing to put a license on this repo, maybe something like MIT? I wonder if having no license even allows projects to use this?

**Comment by DianaIonita** [comment]
Hi @mitchellsimoens,

Thanks for your question. The [package.json](https://github.com/DianaIonita/serverless-api-gateway-caching/blob/develop/package.json#L19) does mention a license, is that what you're referring to, or is it something else?

**Comment by mitchellsimoens** [comment]
I think if you add a LICENSE file then GitHub will also grab this and display it properly also. An example is over on the [react repo](https://github.com/facebook/react):

![react repo](https://user-images.githubusercontent.com/325473/153226309-6ee42ba1-925b-4357-a29f-27383779905a.png)

I see you are using ISC so you could copy/paste from https://choosealicense.com/licenses/isc/

**Comment by DianaIonita** [comment]
Thank you, @mitchellsimoens, for the clarification, I just added the license file to this repo.
