### ISSUE TITLE
support for httpApi

### ISSUE THREAD

**Issue by oreporan** [DianaIonita/serverless-api-gateway-caching#112]
Hey

Right now this library doesn't seem to support the http v2 (httpApi) serverless event

https://www.serverless.com/framework/docs/providers/aws/events/http-api/

**Comment by DianaIonita** [comment]
Hi @oreporan,

Thanks for raising this issue.
According to AWS [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html), HTTP API does not currently support API Gateway caching:

![image](https://user-images.githubusercontent.com/2750493/181028227-a93d799e-27ed-49a6-8033-a28d811d30fa.png)
