### ISSUE TITLE
Support API Gateway V2

### ISSUE THREAD

**Issue by JoepdeJong** [DianaIonita/serverless-api-gateway-caching#114]
Is it possible to make this caching plugin compatible with `httpApi` of API Gateway V2?

**Comment by DianaIonita** [comment]
Hi @JoepdeJong ,

Thanks for your question.
According to AWS [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html), HTTP API does not currently support API Gateway caching:

![image](https://user-images.githubusercontent.com/2750493/181028227-a93d799e-27ed-49a6-8033-a28d811d30fa.png)
