### ISSUE TITLE
Is there a way to invalidate all caches for a specific key?

### ISSUE THREAD

**Issue by pavlelekic** [DianaIonita/serverless-api-gateway-caching#121]
Let’s say I have two cache keys, I want to be able to invalidate all caches for A = 4 and B = any value. Is there a symbol, like a `*` that I could use to signal to ApiGateway I want to invalidate specifically A = 4 and all values of B?

Thanks!

**Comment by pavlelekic** [comment]
Because if the `*` operator doesn’t exist, I would have to fire requests for all possible combinations of A and B where A = 4. With 2 parameters that is not a big deal, but if I have 5 different parameters, and some of those parameters have large pools of possible values then the number of possible combinations is huge.

**Comment by DianaIonita** [comment]
Hi @pavlelekic,

Thank you for raising the issue. I'm not aware of any API Gateway feature that allows cache invalidation for multiple keys at the same time, unfortunately.
If your architecture allows it, perhaps when one parameter changes, you can trigger a Lambda function which fires off cache invalidation requests for the parameter combination you requested - or, simply, flush the entire cache if it's easier that way.
