### ISSUE TITLE
Is it possible to ignore non 200 responses?

### ISSUE THREAD

**Issue by chris-munn** [DianaIonita/serverless-api-gateway-caching#125]
Apologies if i've missed this in the documentation, but is it possible to ignore or invalidate the cache based on response codes?

**Comment by DianaIonita** [comment]
Hi @pavlelekic,

Thank you for raising this issue.
This plugin is a wrapper around the API Gateway caching functionality, so if API Gateway supported it, then I would have been able to add support for it as well. Unfortunately, according to [this issue on StackOverflow](https://stackoverflow.com/questions/45883323/prevent-caching-of-non-200-responses-in-aws-api-gateway), it doesn't seem like it's possible to disable caching based on response codes. There are some suggestions in there about how one may invalidate the cache by sending the `cache-control` header, if that helps.
