### ISSUE TITLE
API gateway cacheKeyParameters error

### ISSUE THREAD

**Issue by donald-labajo-wimp2warrior** [DianaIonita/serverless-api-gateway-caching#136]
![image](https://github.com/DianaIonita/serverless-api-gateway-caching/assets/93166799/dcb93cec-e53c-4452-8a4d-c02593192d27)

see image above for cacheKeyParameters.
Deploying the stack, we are getting this error on cloudformation:

![image](https://github.com/DianaIonita/serverless-api-gateway-caching/assets/93166799/66332b23-b8a8-441b-83af-16ba4892d68e)

Tried researching but to no avail. I also tried updating our serverless-api-gateway-caching from v1.7.4 to v1.9.0 but issue still persists.
Removing all cacheKeyParameters, deployment goes through.

For context, we are running:
- serverless framework v2
- serverless-api-gateway-caching@v1.7.4
- serverless-webpack@v5.5.5
- nodejs14.x

Based on docs - https://github.com/DianaIonita/serverless-api-gateway-caching we are using the correct format ie caching>cacheKeyParameters>[set of parameters]

Please help
Thanks!

PS: The config was runnin fine until March13, 2024

**Comment by DianaIonita** [comment]
Hi @donald-labajo-wimp2warrior,

Thanks for raising this issue!
Please update your `serverless-api-gateway-caching` module to `v1.10.3` and let me know if you're still having trouble.

**Comment by donald-labajo-wimp2warrior** [comment]
Hi @DianaIonita, it appears to be working now. Thank you so much! ✨
