### ISSUE TITLE
Multiple HTTP events and custom name

### ISSUE THREAD

**Issue by LuciCondescu** [DianaIonita/serverless-api-gateway-caching#19]
Hi @DianaIonita,

I've just created a pull request which adds support for multiple HTTP events and allows the user to have a custom name for the lambda functions: https://github.com/DianaIonita/serverless-api-gateway-caching/pull/18. Maybe take a look and let me know what you think :)

Luci

**Comment by DianaIonita** [comment]
Merged and released.
Cheers!
