### ISSUE TITLE
Two-step deployment - No Rest API found. Caching settings will not be updated.

### ISSUE THREAD

**Issue by triqi** [DianaIonita/serverless-api-gateway-caching#34]
## Summary
The plugin throws a `[serverless-api-gateway-caching] No Rest API found. Caching settings will not be updated.` in a two-step serverless deployment process.
1. `severless package`
2. `severless deploy --package .serverless`

## Solution hints
The problem may lie in the check for the weather a Rest API Gateway resource is defined ([src here](https://github.com/DianaIonita/serverless-api-gateway-caching/blob/c3f777be7165d01530428d30f5b34c98f709bf8c/src/apiGatewayCachingPlugin.js#L42)).
This check might need to perform a re-evaluation of `this.thereIsARestApi = restApiExists(this.serverless);`.

**Comment by DianaIonita** [comment]
Thanks for finding and fixing this, I've just released [v1.3.2](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.3.2) containing this change.
