### ISSUE TITLE
Error: Update size too large. Try updating stage in multiple UpdateStage operations

### ISSUE THREAD

**Issue by afarqu** [DianaIonita/serverless-api-gateway-caching#46]
This error occurs when a large number of APIs exist in the template. The AWS updateStage call can only take a smaller batch of operations.

I suggest that the calls to updateStage be batched. If you want I can create a PR with my changes if you want.

**Comment by daniyals** [comment]
Im getting the same error

**Comment by DianaIonita** [comment]
Hi @afarqu and @daniyals,
How many functions have you defined in your `serverless.yml`?

**Comment by daniyals** [comment]
22 functions

**Comment by DianaIonita** [comment]
Hi @afarqu and @daniyals,

I've just released [v1.3.6](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.3.6) which should fix this issue.
