### ISSUE TITLE
 [serverless-api-gateway-caching] No Rest API found. Caching settings will not be updated - when used in conjunction with serverless-nested-stack.

### ISSUE THREAD

**Issue by kkirov** [DianaIonita/serverless-api-gateway-caching#48]
The serverless-nested-stack breaks down the stacks in few nested stacks to avoid the cloudformation limitation of 200 resources per stack. 
And when I use serverless-nested-stack breaks and serverless-api-gateway-caching I get:
`Serverless: [serverless-api-gateway-caching] No Rest API found. Caching settings will not be updated.`

It seems to me that the code:
https://github.com/DianaIonita/serverless-api-gateway-caching/blob/develop/src/restApiId.js#L15
is not checking in all nested stacks if resource 'ApiGatewayRestApi' exists!
Let me know if you need me to provide any additional information!

**Comment by willfarrell** [comment]
What's the order of your plugins? Order matters.

**Comment by kkirov** [comment]
- serverless-api-gateway-caching
- serverless-nested-stack

but I also tried:
- serverless-nested-stack
- serverless-api-gateway-caching

and I get the same result.

**Comment by webchaz** [comment]
I'm getting this same issue using `serverless-plugin-split-stacks` have also tried multiple order for including these.  Any chance you found a solution to this?

**Comment by simqel** [comment]
For now, the only solution that I've found is to set `restApiId` and `restApiRootResourceId`:

```
provider:
  apiGateway:
    restApiId: xxxxx
    restApiRootResourceId: xxxxx
```

How to get them: https://serverless.com/framework/docs/providers/aws/events/apigateway#manually-configuring-shared-api-gateway

Can be also set separately for stages using `custom` section and variables.

**Comment by chaitanya11** [comment]
I am also facing same issue when used with `serverless-plugin-split-stacks`.

**Comment by BorjaMacedo** [comment]
If you are using split stack you need it to place the AWS :: ApiGateway :: RestApi resource in the root. To cause that you need to use the file stacks-map.js.
```javascript
if (resource.Type.includes('AWS::ApiGateway::RestApi')) {
            return false;
}
```

Be careful, returning null or undefined is not enough.

**Comment by DianaIonita** [comment]
The latest version of the plugin, [1.7.3](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.7.3), now has an improved way of finding the Rest API id, which should make it work with stack splitting plugins. The changes applied are in [this PR](https://github.com/DianaIonita/serverless-api-gateway-caching/pull/93) if anyone is curious.

Please feel free to reopen the issue or raise a new one if you're still having problems.
