### ISSUE TITLE
Problem in deploying ttlInSeconds and perKeyInvalidation

### ISSUE THREAD

**Issue by ankitbhansali** [DianaIonita/serverless-api-gateway-caching#54]
Following are my global properties

> custom:
>   configFile: ${file(../config.${self:provider.stage}.yml)}
>   apiGatewayCaching:
>     enabled: true
>     clusterSize: '0.5' # defaults to '0.5'
>     dataEncrypted: true
>     ttlInSeconds: 900 # defaults to the maximum allowed: 3600
>     perKeyInvalidation:
>       requireAuthorization: false

and my function has these cache properties.

> caching:
>            enabled: true
>            cacheKeyParameters:
>               - name: request.path.proxy

The properties ttlInSeconds and perKeyInvalidation are not reflected on API Gateway console when i deploy this. All other properties can be verified. 
Can someone please suggest ?

**Comment by akleiber** [comment]
are the settings not reflected in the global settings or per method settings?
take a look at API GW UI and check the method settings

**Comment by ankitbhansali** [comment]
Ooh ok method settings are correct. 
So only global settings are not updated. Got it. Thanks.
