### ISSUE TITLE
Support for shared api gateway

### ISSUE THREAD

**Issue by apalumbo** [DianaIonita/serverless-api-gateway-caching#56]
We are sharing out api gateway in multiple sub stack (not using the plugin but splitting the stacks manually).
Now if we use the plugin in more than one stack the base configuration will be updated from each stack (like cache enable or cluster size).
I've created a PR to support this use case it would be nice to have this feature integrated #55

**Comment by DianaIonita** [comment]
Thanks, released as part of [1.4.0](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.4.0)
