### ISSUE TITLE
Cache miss and no cache when using custom domain

### ISSUE THREAD

**Issue by joaolcorreia** [DianaIonita/serverless-api-gateway-caching#78]
Hi, I followed the instructions, Im using a custom domain. When calling the function directly I always see a cache miss and when using the custom domain I dont even see the cache header.

Are there any instructions with detailed steps?

Thanks
Joao

**Comment by DianaIonita** [comment]
Hi @joaolcorreia,

Thanks for raising this issue. A custom domain should make no difference to this plugin. Would you mind sharing your `serverless.yml` configuration please?
Also, what do you mean when you say that you see a cache miss? What are you looking for in the response?

**Comment by DianaIonita** [comment]
Closing the issue, please reopen if there are any updates.
