### ISSUE TITLE
Not using AWS profile

### ISSUE THREAD

**Issue by kettunen** [DianaIonita/serverless-api-gateway-caching#8]
Hi,
thanks for the plugin. I found one problem with it. If I run it with...
`sls deploy --stage dev --aws-profile profile`
.. I got "The security token included in the request is invalid.".

If I export the aws credentials and run it with...
`sls deploy --stage dev`
... then it works like expected.

So it seems that it can't use credentials from profile.

**Comment by DianaIonita** [comment]
Hi @kettunen,
Thanks for reporting this. It should now be fixed in version [1.1.1](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.1.1) of the plugin.
Please reopen the issue if it still doesn't work for you.

**Comment by kettunen** [comment]
That was fast! It works perfectly now. Thanks @DianaIonita
