### ISSUE TITLE
Configuration schema extension does not pass strict validation mode

### ISSUE THREAD

**Issue by pgrzesik** [DianaIonita/serverless-api-gateway-caching#98]
Hello,

along with the upcoming `v3` release of the Serverless Framework, internal schema validation has been improved and now enforces `strict` validation mode. Unfortunately, after preliminary tests, it seems like the schema extension implemented in this plugin does not adhere to strict validation rules and needs to be adjusted in order to support `v3` release of the Framework. The best way to verify that is to use the plugin along with the latest `v3` prerelease (or official release soon). 

I'm happy to answer any additional questions.

**Comment by DianaIonita** [comment]
Hi @pgrzesik

Thanks for raising the issue and the associated PR with a fix! I just had a play with the `pre-3` version of `serverless` and the latest version of this plugin (1.7.4) and there don't seem to be any validation issues. That said, I believe your change is low-risk and it's worth merging it in. Much appreciated!

**Comment by pgrzesik** [comment]
Hello @DianaIonita 👋 The strict schema validation was introduced at a later point in time for `pre-3` release so maybe you tested with the version that didn't include the change yet? Thanks a lot for quick response and for maintaining plugins and helping Serverless ecosystem grow 🙌

**Comment by DianaIonita** [comment]
Hi @pgrzesik,

I tested with the latest `pre-3` version as it appeared on `npm` yesterday, but who knows, maybe a fluke somewhere. The change you made is useful nonetheless.
Thank you very much for your kind words. I am glad to be able to help!
